import Head from "next/head";
import CharacterCard from "../components/CharacterCard";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";

export default function Home({characters}) {

  const container = {
    hidden: { scale: 0 },
    show: {
      scale: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <motion.ul
        variants={container}
        initial="hidden"
        animate="show"
        className={styles.characterGrid}
      >
        {characters.results.map((item) => (
          <CharacterCard key={item.id} character={item} />
        ))}
      </motion.ul>
    </div>
  );
}

export const getStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character/')
  const characters = await res.json()

  return {
    props: {
      characters,
    },
    revalidate: 10,
  }
}
